import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import fs from 'fs';
import path from 'path';
import os from 'os';

// Locate the certificates generated by 'npx office-addin-dev-certs install'
const homeDir = os.homedir();
const certFolder = path.join(homeDir, ".office-addin-dev-certs");
const keyPath = path.join(certFolder, "localhost.key");
const certPath = path.join(certFolder, "localhost.crt");
const serverConfig = {
  port: 3000,
  https: {
    key: fs.readFileSync(keyPath),
    cert: fs.readFileSync(certPath),
  }};

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const isDev = mode === 'development';

  return {
    plugins: [react(), tailwindcss()],
    ...(isDev && {server: serverConfig}),
    ...(!isDev && {base: '/book-analysis/'}),
  };
});
