import { defineConfig } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import fs from 'fs';
import path from 'path';
import os from 'os';

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const isDev = mode === 'development';

  let serverConfig = false;
  if (isDev){
    // Locate the certificates generated by 'npx office-addin-dev-certs install'
    const homeDir = os.homedir();
    const certFolder = path.join(homeDir, ".office-addin-dev-certs");
    const keyPath = path.join(certFolder, "localhost.key");
    const certPath = path.join(certFolder, "localhost.crt");
    serverConfig = {
      port: 3000,
      https: {
        key: fs.readFileSync(keyPath),
        cert: fs.readFileSync(certPath),
      }};
  }

  const makeProdManifest = () => viteStaticCopy({
    targets: [
      {
        src: 'manifest.xml',
        dest: './', // Copies to the root of 'dist'
        rename: 'book-analysis.xml',
        transform: (content) => content.toString().replace(/localhost:3000/g, 'carsten-greve.github.io/book-analysis'),
      },
    ],
  });

  return {
    plugins: [
      react(),
      tailwindcss(),
      makeProdManifest()
    ],
    ...(isDev && {server: serverConfig}),
    ...(!isDev && {base: '/book-analysis/'}),
  };
});
